name: Non-main CI
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install prerequisites
        run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Cache build
        uses: actions/cache@v4.2.3
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --profile release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Load cached build
        uses: actions/cache@v4.2.3
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Test
        run: cargo test --profile release