name: Main CI
on:
  push:
#    ZJ-TODO: only on main once working
#    branches:
#      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v5
      - name: Cache build
        uses: actions/cache@v4.2.3
        with:
          path: |
            target/
            wasm_out/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --profile release

  build_wasm:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v5
      - name: Cache build
        uses: actions/cache@v4.2.3
        with:
          path: |
            target/
            wasm_out/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Build
        run: |
          ./scripts/build-wasm.sh

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Load cached build
        uses: actions/cache@v4.2.3
        with:
          path: |
            target/
            wasm_out/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Test
        run: cargo test --profile release

  upload:
    runs-on: self-hosted
    needs: [build_wasm, test]

    steps:
      - uses: actions/checkout@v4
      - name: Load cached build
        uses: actions/cache@v4.2.3
        with:
          path: |
            target/
            wasm_out/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Itch.io Upload
        env:
          ITCH_BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
        run: |
          wget -O butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          export PATH="$PATH:$(pwd)/butler"
          echo "$PATH"
          echo "$ITCH_BUTLER_CREDENTIALS" > butler_creds
          echo "$(ls -la)"
          butler login -i butler_creds
          ./scripts/itch-upload.sh